# Generated by Django 5.1.1 on 2024-10-17 01:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.CharField(max_length=100)),
                ('htmweekday', models.IntegerField()),
                ('htmweekend', models.IntegerField()),
                ('description', models.TextField()),
                ('gmapsurl', models.URLField(max_length=500)),
            ],
        ),
    ]
