# Generated by Django 5.1.1 on 2024-10-23 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attraction', '0003_touristattraction_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristattraction',
            old_name='gmapsurl',
            new_name='gmaps_url',
        ),
        migrations.RenameField(
            model_name='touristattraction',
            old_name='htmweekday',
            new_name='htm_weekday',
        ),
        migrations.RenameField(
            model_name='touristattraction',
            old_name='htmweekend',
            new_name='htm_weekend',
        ),
        migrations.RenameField(
            model_name='touristattraction',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='touristattraction',
            old_name='attraction_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
