# Generated by Django 5.1.1 on 2024-10-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('food_preference', models.CharField(max_length=255)),
                ('average_price', models.FloatField()),
                ('rating', models.FloatField()),
                ('atmosphere_type', models.CharField(max_length=255)),
                ('food_variations', models.CharField(max_length=255)),
            ],
        ),
    ]
