# Generated by Django 5.1.1 on 2024-10-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_harga_rata_rata_makanan_di_toko_restaurant_harga_rata_rata_makanan_di_toko_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='jenis_suasana',
            new_name='atmosphere',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='harga_rata_rata_makanan_di_toko',
            new_name='average_price',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='preferensi_makanan',
            new_name='food_preference',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='variasi_makanan',
            new_name='food_variety',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='nama_restoran',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating_toko',
            new_name='rating',
        ),
    ]
