# Generated by Django 5.1.1 on 2024-10-24 18:56

from django.db import migrations
import os
from django.core.management import call_command
from django.conf import settings


def load_my_initial_data(apps, schema_editor):
    # Construct the full path to the JSON file in the static/data folder
    json_file_path = os.path.join(settings.BASE_DIR, 'static', 'data', 'Kuliner.json')
    
    # Call loaddata with the full path
    call_command("loaddata", json_file_path)

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_jenis_suasana_restaurant_atmosphere_and_more'),
    ]

    operations = [migrations.RunPython(load_my_initial_data)
    ]
