# Generated by Django 5.1.2 on 2024-10-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_booking_bookingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='booking_id',
        ),
    ]
