# Generated by Django 5.1.1 on 2024-10-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_display', '0002_rssitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
