# Generated by Django 5.1.1 on 2024-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_display', '0003_alter_rssitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
